sudo: required

language: c

services:
- docker

env:
  global:
  - CI_DOCKER_IMAGE=buildpack-deps:sid
  - DOCKER_EXEC_ROOT="docker exec --user root test_container"
  - DOCKER_EXEC="docker exec test_container"

before_install:
- docker pull $CI_DOCKER_IMAGE
- |
  docker run --detach --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR} \
    ${CI_DOCKER_IMAGE} \
    /bin/bash

install:
- ${DOCKER_EXEC_ROOT} apt-get update --quiet --quiet
- ${DOCKER_EXEC_ROOT} apt-get install --no-install-recommends --yes
    autoconf-archive
    build-essential
    gtk-doc-tools
    libglib2.0-dev
    libgudev-1.0-dev
- ${DOCKER_EXEC} gcc --version

script:
- ${DOCKER_EXEC} ./autogen.sh --enable-gtk-doc
- ${DOCKER_EXEC} make V=1 -j $(nproc)
- ${DOCKER_EXEC} sh -c 'make install V=1 DESTDIR=$(pwd)/x && rm -rf $(pwd)/x'
- ${DOCKER_EXEC} make V=1 install
- ${DOCKER_EXEC} make V=1 distcheck
- ${DOCKER_EXEC} make V=1 clean
- git status

notifications:
  slack:
    secure: Ai0cehpSN+rRi0hstVxXDKW5BwYMvxbhnd1Dd0tgS7iC+rsaU+BzGr4nLj+3SYFzFVJM4OjL86VBwN+PAfdv4wX+SKuxvePwAOEDurmXxK8Pl1DgKaOUC7SeD5efpJ9nWMG9HS7i8M7pDclGrbQow6opMQDSWSfmyoowwF4wTRS5Iil/tiTuYVLiIsvEJx7wTydINGYDOI6yyPlidHSll6iyl5RwCAwFmJkmkJ/nebpAb+DuFROXs9WHCKQ8CXXnSEh6ac3t/RN9wWVp/oMAjeeGGZLImmVFfltNV/aH1OW5TGDa6mNui4Sj6+e0gWk6STQi/TpDdgdUALP1ze8LM0iOhTkZBNOnQJPAtiEO1YNDk0LTXMXzTWacc67n79EwY6FTe5bY216hXl1Xl5iWTBUz3WRkQLngXEuBXD7hRQalqWFbB1q0ZLIZuEy9ont7/Aj09TeQS9dkc6kJP5QgisjJISzn/t2R+DVXSws5E9BMEDNdi6JsU/oYyX2JzOSxk5ZMQCOBHUjX0p/IQWsDOGExEKNzIipnHJnF2UoUf0CmHodFciCv8EzCSX2Fh+akYA4kK8N8yzwr8x1T3psE/lxyxJ27WCAc14eoT4VBSukXVkOcfd377mG4fhcehESWavF1HWZn1tHBGtDF7b+VEgQSyPU/o60WynKsWviYHbI=
